# Generated by Django 5.2.14 on 2026-09-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('opcao_a', models.TextField()),
                ('opcao_b', models.TextField()),
                ('opcao_c', models.TextField()),
                ('alternativa_correta', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], max_length=1)),
                ('categoria', models.CharField(choices=[('democracia', 'Democracia e Cidadania'), ('desinformacao', 'Desinformação'), ('checagem', 'Checagem de Informação'), ('trabalhista', 'Direitos Trabalhistas')], max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='Anônimo', max_length=120)),
                ('pontuacao', models.IntegerField(default=0)),
                ('total_perguntas', models.IntegerField(default=0)),
                ('resultado', models.CharField(blank=True, default='', max_length=200)),
                ('respostas', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
