# Generated by Django 5.2.14 on 2026-09-28 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pergunta_resultado_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Direitos Trabalhistas', 'Direitos Trabalhistas'), ('Democracia', 'Democracia'), ('Cidadania', 'Cidadania'), ('Desinformação', 'Desinformação'), ('Educação', 'Educação')], max_length=40)),
                ('content', models.TextField()),
                ('media_type', models.CharField(choices=[('image', 'Foto'), ('video', 'Vídeo')], default='image', max_length=10)),
                ('media_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
