import { CommonModule } from '@angular/common';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';

import { apiConfig } from '../../api-config';

interface Post { id:number; author:string; title:string; category:string; content:string; media_type:'image'|'video'; media_url:string; likes_count:number; comments_count:number; liked_by_me:boolean; }
interface Comment { author:string; content:string; }

@Component({
  selector:'app-postagens', standalone:true, imports:[CommonModule, FormsModule, RouterLink],
  template:`<main class="posts-page"><header class="posts-head"><div><p class="eyebrow">Comunidade</p><h1>Postagens</h1><p>Ideias, informação e conversa pública em um só lugar.</p></div><a routerLink="/publicar">+ Publicar</a></header><section class="feed">@for(post of posts; track post.id){<article class="post"><div class="post-top"><div class="avatar">{{ post.author.charAt(0).toUpperCase() }}</div><div><strong>{{post.author}}</strong><span>{{post.category}}</span></div></div><h2>{{post.title}}</h2><p>{{post.content}}</p>@if(post.media_url){@if(post.media_type === 'image'){<img class="media" [src]="post.media_url" [alt]="post.title" />}@else{<a class="video" [href]="post.media_url" target="_blank" rel="noopener">▶ Abrir vídeo</a>}}<div class="actions"><button type="button" [class.liked]="post.liked_by_me" (click)="like(post)">♥ {{post.likes_count}}</button><button type="button" (click)="toggleComments(post)">▢ {{post.comments_count}} comentários</button></div>@if(openPost === post.id){<div class="comments">@for(comment of comments; track comment.author + comment.content){<p><strong>{{comment.author}}</strong> {{comment.content}}</p>}<div class="comment-form"><input [(ngModel)]="commentText" placeholder="Escreva um comentário" /><button type="button" (click)="comment(post)">Enviar</button></div></div>}</article>} @empty {<div class="empty">Ainda não há publicações. Seja a primeira pessoa a compartilhar uma ideia.</div>}</section></main>`,
  styles:[`:host{display:block}.posts-page{max-width:900px;margin:0 auto;padding:3rem 1.5rem 5rem}.posts-head{display:flex;justify-content:space-between;align-items:end;gap:1rem;margin-bottom:2rem}.posts-head h1{font-size:clamp(2.6rem,6vw,5rem);line-height:1;margin:.3rem 0;color:#0d2d6b}.posts-head p{color:#526278}.posts-head a{background:#0d2d6b;color:#fff;text-decoration:none;border-radius:999px;padding:.9rem 1.2rem;font-weight:800;white-space:nowrap}.eyebrow{text-transform:uppercase;letter-spacing:.12em;color:#1b7a43;font-weight:800}.feed{display:grid;gap:1.2rem}.post{background:#fff;border:1px solid rgba(13,45,107,.08);border-radius:24px;padding:1.5rem;box-shadow:0 16px 35px rgba(13,45,107,.07)}.post-top{display:flex;align-items:center;gap:.75rem}.post-top strong,.post-top span{display:block}.post-top span{color:#718096;font-size:.8rem}.avatar{width:44px;height:44px;border-radius:50%;display:grid;place-items:center;background:linear-gradient(135deg,#f0bf2d,#2cae5f);color:#0d2d6b;font-weight:900}.post h2{margin:1rem 0 .5rem;color:#0d2d6b}.post>p{line-height:1.65;color:#394b62}.media{width:100%;max-height:420px;object-fit:cover;border-radius:16px;margin-top:1rem}.video{display:block;margin-top:1rem;padding:3rem;text-align:center;border-radius:16px;background:linear-gradient(135deg,#0d2d6b,#2cae5f);color:#fff;text-decoration:none;font-weight:800}.actions{display:flex;gap:.7rem;margin-top:1rem;border-top:1px solid #edf1f5;padding-top:1rem}.actions button{border:0;background:transparent;color:#526278;font-weight:800;cursor:pointer}.actions button.liked{color:#c62828}.comments{margin-top:1rem;padding-top:1rem;border-top:1px solid #edf1f5}.comments p{color:#526278}.comment-form{display:flex;gap:.5rem}.comment-form input{flex:1;border:1px solid #d7e0eb;border-radius:999px;padding:.7rem 1rem}.comment-form button{border:0;border-radius:999px;background:#0d2d6b;color:#fff;padding:.7rem 1rem;font-weight:700}.empty{padding:3rem;text-align:center;background:#fff;border-radius:24px;color:#526278}@media(max-width:600px){.posts-page{padding:1.5rem 1rem 3rem}.posts-head{align-items:start;flex-direction:column}.comment-form{flex-direction:column}}`]
})
export class PostagensComponent implements OnInit {
  posts:Post[]=[]; openPost:number|null=null; comments:Comment[]=[]; commentText=''; private readonly api=apiConfig.baseUrl;
  constructor(private http:HttpClient){}
  ngOnInit():void{this.load();}
  load():void{this.http.get<Post[]>(`${this.api}/posts/`).subscribe({next:p=>this.posts=p,error:()=>this.posts=[]});}
  like(post:Post):void{this.http.post<{liked:boolean;likes_count:number}>(`${this.api}/posts/${post.id}/like/`,{}, {headers:this.headers()}).subscribe({next:r=>{post.liked_by_me=r.liked;post.likes_count=r.likes_count;}});}
  toggleComments(post:Post):void{this.openPost=this.openPost===post.id?null:post.id;if(this.openPost){this.http.get<Comment[]>(`${this.api}/posts/${post.id}/comments/`,{headers:this.headers()}).subscribe({next:c=>this.comments=c});}}
  comment(post:Post):void{if(!this.commentText.trim())return;this.http.post<Comment>(`${this.api}/posts/${post.id}/comments/`,{content:this.commentText.trim()},{headers:this.headers()}).subscribe({next:c=>{this.comments=[...this.comments,c];post.comments_count++;this.commentText='';}});}
  private headers():HttpHeaders{return new HttpHeaders({Authorization:`Token ${localStorage.getItem('cidadania_token')||''}`});}
}
